import os
import sys

from flask import Flask, request, jsonify
from flask_socketio import SocketIO

from engineio.async_drivers import gevent

base_dir = '.'
if hasattr(sys, '_MEIPASS'):
    base_dir = os.path.join(sys._MEIPASS)

app = Flask(__name__, static_folder=os.path.join(base_dir, "static"))

app.config['SECRET_KEY'] = 'secret!'

socketio = SocketIO(app, cors_allowed_origins="*", async_mode="gevent")

game_data = {"cards": [
    {"price": "10", "name": "Acquired Company", "tags": ["earth"], "number": "106", "type": "Automated",
     "text": "Increase your MC production 3 steps.", "ae": ""},
    {"price": "12", "name": "Adaptation Technology", "tags": ["science"], "number": "153", "type": "Active", "text": "",
     "ae": "Effect: Your global requirements are +2 or -2 steps, your choice in each case."},
    {"price": "9", "name": "Adapted Lichen", "tags": ["plant"], "number": "48", "type": "Automated",
     "text": "Increase your plant production 1 step.", "ae": ""},
    {"price": "9", "name": "Advanced Alloys", "tags": ["science"], "number": "71", "type": "Active", "text": "",
     "ae": "Effect: Each titanium you have is worth 1MC extra. Each steel you have is worth 1 MC extra."},
    {"price": "11", "name": "Advanced Ecosystems", "tags": ["microbe", "plant", "animal"], "number": "135",
     "type": "Automated", "text": "Requires a plant tag, a microbe tag, and an animal tag.", "ae": ""},
    {"price": "11", "name": "Aerial Mappers", "tags": ["venus"], "number": "213", "type": "Active", "text": "",
     "ae": "Action: Add 1 floater to ANY card, or spend 1 floater here to draw a card."},
    {"price": "26", "name": "Aerobraked Ammonia Asteroid", "tags": ["space", "event"], "number": "170", "type": "Event",
     "text": "Add 2 microbes to ANOTHER card. Increase your heat production 3 steps and your plant production 1 step.",
     "ae": ""}, {"price": "7", "name": "Aerosport Tournament", "tags": ["event"], "number": "214", "type": "Event",
                 "text": "Requires that you have 5 floaters. Gain 1 MC for each city tile in play.", "ae": ""},
    {"price": "21", "name": "AI Central", "tags": ["science", "building"], "number": "208", "type": "Active",
     "text": "Requires 3 science tags to play. Decrease your energy production 1 step.", "ae": "Action: Draw 2 cards."},
    {"price": "0", "name": "Air Raid", "tags": ["event"], "number": "C02", "type": "Event",
     "text": "Requires that you lose 1 floater. Steal 5 MC from any player.", "ae": ""},
    {"price": "13", "name": "Air-Scrapping Expedition", "tags": ["venus", "event"], "number": "215", "type": "Event",
     "text": "Raise Venus 1 step. Add 3 floaters to ANY VENUS CARD.", "ae": ""},
    {"price": "11", "name": "Airliners", "tags": [], "number": "C01", "type": "Automated",
     "text": "Requires that you have 3 floaters. Increase your MC production 2 steps. Add 2 floaters to ANOTHER card.",
     "ae": ""}, {"price": "10", "name": "Algae", "tags": ["plant"], "number": "47", "type": "Automated",
                 "text": "Requires 5 ocean tiles. Gain 1 plant and increase your plant production 2 steps.", "ae": ""},
    {"price": "14", "name": "Anti-Gravity Technology", "tags": ["science"], "number": "150", "type": "Active",
     "text": "Requires 7 science tags.", "ae": "Effect: when you play a card, you pay 2 MC less for it."},
    {"price": "9", "name": "Ants", "tags": ["microbe"], "number": "35", "type": "Active",
     "text": "Requires 4% oxygen. 1 VP per 2 microbes on this card.",
     "ae": "Action: Remove 1 microbe from any card to add 1 to this card."},
    {"price": "18", "name": "Aquifer Pumping", "tags": ["building"], "number": "187", "type": "Active", "text": "",
     "ae": "Action: Spend 8 MC to place 1 ocean tile. STEEL MAY BE USED as if you were playing a building card."},
    {"price": "6", "name": "Archaebacteria", "tags": ["microbe"], "number": "42", "type": "Automated",
     "text": "It must be -18\ufffdC or colder. Increase your plant production 1 step.", "ae": ""},
    {"price": "12", "name": "Arctic Algae", "tags": ["plant"], "number": "23", "type": "Active",
     "text": "It must be -12\ufffdC or colder to play. Gain 1 plant.",
     "ae": "Effect: When anyone places an ocean tile, gain 2 plants."},
    {"price": "15", "name": "Artificial Lake", "tags": ["building"], "number": "116", "type": "Automated",
     "text": "Requires -6\ufffdC or warmer. Place 1 ocean tile ON AN AREA NOT RESERVED FOR OCEAN.", "ae": ""},
    {"price": "12", "name": "Artificial Photosynthesis", "tags": ["science"], "number": "115", "type": "Automated",
     "text": "Increase your plant production 1 step or your energy production 2 steps.", "ae": ""},
    {"price": "14", "name": "Asteroid", "tags": ["space", "event"], "number": "9", "type": "Event",
     "text": "Raise temperature 1 step and gain 2 titanium. Remove up to 3 plants from any player.", "ae": ""},
    {"price": "30", "name": "Asteroid Mining", "tags": ["space", "jovian"], "number": "40", "type": "Automated",
     "text": "Increase your titanium production 2 steps.", "ae": ""},
    {"price": "13", "name": "Asteroid Mining Consortium", "tags": ["jovian"], "number": "2", "type": "Automated",
     "text": "Requires that you have titanium production. Decrease any titanium production 1 step and increase your own 1 step.",
     "ae": ""},
    {"price": "10", "name": "Atalanta Planitia Lab", "tags": ["science", "venus"], "number": "216", "type": "Automated",
     "text": "Requires 3 science tags. Draw 2 cards.", "ae": ""},
    {"price": "15", "name": "Atmo Collectors", "tags": [], "number": "C03", "type": "Active",
     "text": "Add 2 floaters to ANY card.",
     "ae": "Action: Add 1 floater to this card, or spend 1 floater here to gain 2 titanium, or 3 energy, or 4 heat."},
    {"price": "22", "name": "Atmoscoop", "tags": ["space", "jovian"], "number": "217", "type": "Automated",
     "text": "Requires 3 science tags. Either raise the temperature 2 steps, or raise Venus 2 steps. Add 2 floaters to ANY card.",
     "ae": ""},
    {"price": "32", "name": "Beam From a Thorium Asteroid", "tags": ["space", "jovian", "energy"], "number": "58",
     "type": "Automated",
     "text": "Requires a Jovian tag. Increase your heat production and energy production 3 steps each.", "ae": ""},
    {"price": "27", "name": "Big Asteroid", "tags": ["space", "event"], "number": "11", "type": "Event",
     "text": "Raise temperature 2 steps and gain 4 titanium. Remove up to 4 plants from any player.", "ae": ""},
    {"price": "4", "name": "Biomass Combustors", "tags": ["building", "energy"], "number": "183", "type": "Automated",
     "text": "Requires 6% oxygen. Decrease any plant production 1 step and increase your energy production 2 steps.",
     "ae": ""}, {"price": "10", "name": "Birds", "tags": ["animal"], "number": "72", "type": "Active",
                 "text": "Requires 13% oxygen. Decrease any plant production 2 steps. 1 VP for each animal on this card",
                 "ae": "Action: Add an animal to this card."},
    {"price": "15", "name": "Black Polar Dust", "tags": [], "number": "22", "type": "Automated",
     "text": "Place an ocean tile. Decrease your MC production 2 steps and increase your heat production 3 steps.",
     "ae": ""}, {"price": "11", "name": "Breathing Filters", "tags": ["science"], "number": "114", "type": "Automated",
                 "text": "Requires 7% oxygen.", "ae": ""},
    {"price": "7", "name": "Bribed Committee", "tags": ["earth", "event"], "number": "112", "type": "Event",
     "text": "Raise your terraform rating 2 steps.", "ae": ""},
    {"price": "6", "name": "Building Industries", "tags": ["building"], "number": "65", "type": "Automated",
     "text": "Decrease your energy production 1 step and increase your steel production 2 steps.", "ae": ""},
    {"price": "10", "name": "Bushes", "tags": ["plant"], "number": "93", "type": "Automated",
     "text": "Requires -10\ufffdC or warmer. Increase your plant production 2 steps. Gain 2 plants.", "ae": ""},
    {"price": "7", "name": "Business Contacts", "tags": ["earth", "event"], "number": "111", "type": "Event",
     "text": "Look at the top 4 cards from the deck. Take 2 of them into hand and discard the other 2", "ae": ""},
    {"price": "4", "name": "Business Network", "tags": ["earth"], "number": "110", "type": "Active",
     "text": "Decrease your MC production 1 step.",
     "ae": "Action: Look at the top card and either buy it or discard it"},
    {"price": "24", "name": "Callisto Penal Mines", "tags": ["space", "jovian"], "number": "82", "type": "Automated",
     "text": "Increase your MC production 3 steps.", "ae": ""},
    {"price": "26", "name": "Capital", "tags": ["building", "city"], "number": "8", "type": "Automated",
     "text": "Requires 4 ocean tiles. Place [the capital city] tile. Decrease your energy production 2 steps and increase your MC production 5 steps. 1 ADDITIONAL VP FOR EACH OCEAN TILE ADJACENT TO THIS CITY TILE.",
     "ae": ""},
    {"price": "6", "name": "Carbonate Processing", "tags": ["building"], "number": "43", "type": "Automated",
     "text": "Decrease your energy production 1 step and increase your heat production 3 steps.", "ae": ""},
    {"price": "3", "name": "Caretaker Contract", "tags": [], "number": "154", "type": "Active",
     "text": "Requires 0\ufffdC or warmer.", "ae": "Action: Spend 8 heat to increase your terraforming rating 1 step."},
    {"price": "8", "name": "Cartel", "tags": ["earth"], "number": "137", "type": "Automated",
     "text": "Increase your MC production 1 step for each Earth tag you have, including this.", "ae": ""},
    {"price": "1", "name": "CEO's Favourite Project", "tags": ["event"], "number": "149", "type": "Event",
     "text": "Add 1 resource to a card with at least 1 resource on it.", "ae": ""},
    {"price": "11", "name": "Cloud Seeding", "tags": [], "number": "4", "type": "Automated",
     "text": "Requires 3 ocean tiles. Decrease your MC production 1 step and any heat production 1 step. Increase your plant production 2 steps.",
     "ae": ""}, {"price": "8", "name": "Colonizer Training Camp", "tags": ["building", "jovian"], "number": "1",
                 "type": "Automated", "text": "Oxygen must be 5% or less.", "ae": ""},
    {"price": "21", "name": "Comet", "tags": ["space", "event"], "number": "10", "type": "Event",
     "text": "Raise temperature 1 step and place an ocean tile. Remove up to 3 plants from any player.", "ae": ""},
    {"price": "11", "name": "Comet for Venus", "tags": ["space", "event"], "number": "218", "type": "Event",
     "text": "Raise Venus 1 step. Remove up to 4 MC from a player WITH A VENUS TAG IN PLAY.", "ae": ""},
    {"price": "16", "name": "Commercial District", "tags": ["building"], "number": "85", "type": "Automated",
     "text": "Decrease your energy production 1 step and increase your MC production 4 steps. Place [the commercial district] tile. 1 VP PER ADJACENT CITY TILE.",
     "ae": ""}, {"price": "13", "name": "Community Services", "tags": [], "number": "C04", "type": "Automated",
                 "text": "Increase your MC production 1 step per CARD WITH NO TAGS, including this.", "ae": ""},
    {"price": "5", "name": "Conscription", "tags": ["earth", "event"], "number": "C05", "type": "Event",
     "text": "Requires 2 Earth tags. The next card you play this generation costs 16 MC less.", "ae": ""},
    {"price": "15", "name": "Convoy From Europa", "tags": ["space", "event"], "number": "161", "type": "Event",
     "text": "Place 1 ocean tile and draw 1 card.", "ae": ""},
    {"price": "10", "name": "Corona Extractor", "tags": ["space", "energy"], "number": "C06", "type": "Automated",
     "text": "Requires 4 science tags. Increase your energy production 4 steps.", "ae": ""},
    {"price": "11", "name": "Corporate Stronghold", "tags": ["building", "city"], "number": "182", "type": "Automated",
     "text": "Decrease your energy production 1 step and increase your MC production 3 steps. Place a city tile.",
     "ae": ""}, {"price": "8", "name": "Corroder Suits", "tags": ["venus"], "number": "219", "type": "Automated",
                 "text": "Increase your MC production 2 steps. Add 1 resource to ANY VENUS CARD.", "ae": ""},
    {"price": "10", "name": "Cryo-Sleep", "tags": ["science"], "number": "C07", "type": "Active", "text": "",
     "ae": "Effect: When you trade, you pay 1 less resource for it."},
    {"price": "16", "name": "Cupola City", "tags": ["building", "city"], "number": "29", "type": "Automated",
     "text": "Oxygen must be 9% or less. Place a city tile. Decrease your energy production 1 step and increase your MC production 3 steps.",
     "ae": ""}, {"price": "15", "name": "Dawn City", "tags": ["space", "city"], "number": "220", "type": "Automated",
                 "text": "Requires 4 science tags. Decrease your energy production 1 step. Increase your titanium production 1 step. Place a city tile ON THE RESERVED AREA.",
                 "ae": ""},
    {"price": "5", "name": "Decomposers", "tags": ["microbe"], "number": "131", "type": "Active",
     "text": "Requires 3# oxygen. 1 VP per 3 microbes on this card.",
     "ae": "Effect: When you play an animal, plant, or microbe tag, including this, add a microbe to this card."},
    {"price": "13", "name": "Deep Well Heating", "tags": ["building", "energy"], "number": "3", "type": "Automated",
     "text": "Increase your energy production 1 step. Increase temperature 1 step.", "ae": ""},
    {"price": "31", "name": "Deimos Down", "tags": ["space", "event"], "number": "39", "type": "Event",
     "text": "Raise temperature 3 steps and gain 4 steel. Remove up to 8 plants from any player.", "ae": ""},
    {"price": "16", "name": "Designed Microorganisms", "tags": ["science", "microbe"], "number": "155",
     "type": "Automated", "text": "It must be -14\ufffdC or colder. Increase your plant production 2 steps.", "ae": ""},
    {"price": "11", "name": "Deuterium Export", "tags": ["space", "energy", "venus"], "number": "221", "type": "Active",
     "text": "",
     "ae": "Action: Add 1 floater to this card, or spend 1 floater here to increase your energy production 1 step."},
    {"price": "11", "name": "Development Center", "tags": ["science", "building"], "number": "14", "type": "Active",
     "text": "", "ae": "Action: Spend 1 energy to draw a card."},
    {"price": "11", "name": "Dirigibles", "tags": ["venus"], "number": "222", "type": "Active", "text": "",
     "ae": "Action: Add 1 floater to ANY card. Effect: When playing a Venus tag, floaters here may be used as payment, and are worth 3 MC each"},
    {"price": "24", "name": "Domed Crater", "tags": ["building", "city"], "number": "16", "type": "Automated",
     "text": "Oxygen must be 7% or less. Gain 3 plants and place a city tile. Decrease your energy production 1 step and increase MC production 3 steps.",
     "ae": ""}, {"price": "2", "name": "Dust Seals", "tags": [], "number": "119", "type": "Automated",
                 "text": "Requires 3 or less ocean tiles.", "ae": ""},
    {"price": "23", "name": "Earth Catapult", "tags": ["earth"], "number": "70", "type": "Active", "text": "",
     "ae": "Effect: when you play a card, you pay 2 MC less for it."},
    {"price": "43", "name": "Earth Elevator", "tags": ["space", "earth"], "number": "C08", "type": "Automated",
     "text": "Increase your titanium production 3 steps.", "ae": ""},
    {"price": "1", "name": "Earth Office", "tags": ["earth"], "number": "105", "type": "Active", "text": "",
     "ae": "Effect: When you play an Earth tag, you pay 3 MC less for it."},
    {"price": "12", "name": "Ecological Zone", "tags": ["plant", "animal"], "number": "128", "type": "Active",
     "text": "Requires that you have a greenery tile. Place [the Ecological Zone] tile ADJACENT TO ANY GREENERY TILE. 1 VP per 2 animals on this card.",
     "ae": "Effect: When you play an animal or a plant tag (including these 2), add an animal to this card."},
    {"price": "21", "name": "Ecology Research", "tags": ["science", "microbe", "plant", "animal"], "number": "C09",
     "type": "Automated",
     "text": "Increase your plant production 1 step for each colony you own. Add 1 animal to ANOTHER card and 2 microbes to ANOTHER card.",
     "ae": ""}, {"price": "17", "name": "Electro Catapult", "tags": ["building"], "number": "69", "type": "Active",
                 "text": "Oxygen must be 8% or less. Decrease your energy production 1 step.",
                 "ae": "Action: Spend 1 plant or 1 steel to gain 7 MC"},
    {"price": "15", "name": "Energy Saving", "tags": ["energy"], "number": "189", "type": "Automated",
     "text": "Increase your energy production 1 step for each city tile in play.", "ae": ""},
    {"price": "3", "name": "Energy Tapping", "tags": ["energy"], "number": "201", "type": "Automated",
     "text": "Decrease any energy production 1 step and increase your own 1 step.", "ae": ""},
    {"price": "16", "name": "Eos Chasma National Park", "tags": ["building", "plant"], "number": "26",
     "type": "Automated",
     "text": "Requires -128\ufffdC or warmer. Add 1 animal TO ANY ANIMAL CARD. Gain 3 plants. Increase your MC production 2 steps.",
     "ae": ""},
    {"price": "11", "name": "Equatorial Magnetizer", "tags": ["building"], "number": "15", "type": "Active", "text": "",
     "ae": "Action: Decrease your energy production 1 step to increase your terraforming rating 1 step."},
    {"price": "21", "name": "Extractor Balloons", "tags": ["venus"], "number": "223", "type": "Active",
     "text": "Add 3 floaters to this card.",
     "ae": "Action: Add 1 flaoter to this card, or remove 2 floaters here to raise Venus 1 step."},
    {"price": "13", "name": "Extreme-Cold Fungus", "tags": ["microbe"], "number": "134", "type": "Active",
     "text": "It must be -10\ufffdC or colder.", "ae": "Action: Gain 1 plant or add 2 microbes to ANOTHER card."},
    {"price": "3", "name": "Extremophiles", "tags": ["microbe", "venus"], "number": "224", "type": "Active",
     "text": "Requires 2 science tags. 1 VP for per 3 microbes on this card.",
     "ae": "Action: Add 1 microbe to ANY card."},
    {"price": "16", "name": "Farming", "tags": ["plant"], "number": "118", "type": "Automated",
     "text": "Requires +4\ufffdC or warmer. Increase your MC production 2 steps and your plant production 2 steps. Gain 2 plants.",
     "ae": ""}, {"price": "9", "name": "Fish", "tags": ["animal"], "number": "52", "type": "Active",
                 "text": "Requires 2\ufffdC or warmer. Decrease any plant production 1 step. 1 VP for each animal on this card.",
                 "ae": "Action: Add 1 animal to this card."},
    {"price": "3", "name": "Floater Leasing", "tags": [], "number": "C10", "type": "Automated",
     "text": "Increase your MC production 1 step per 3 floaters you have.", "ae": ""},
    {"price": "2", "name": "Floater Prototypes", "tags": ["science", "event"], "number": "C11", "type": "Event",
     "text": "Add 2 floaters to ANOTHER card", "ae": ""},
    {"price": "7", "name": "Floater Technology", "tags": ["science"], "number": "C12", "type": "Active", "text": "",
     "ae": "Action: Add 1 floater to ANOTHER card."},
    {"price": "5", "name": "Floating Habs", "tags": ["venus"], "number": "225", "type": "Active",
     "text": "Requires 2 science tags. 1 VP per 2 floaters on this card.",
     "ae": "Action: Spend 2 MC to add 1 floater to ANY card."},
    {"price": "7", "name": "Flooding", "tags": ["event"], "number": "188", "type": "Event",
     "text": "Place an ocean tile. IF THERE ARE TILES ADJACENT TO THIS OCEAN TILE, YOU MAY REMOVE 4 MC FROM THE OWNER OF ONE OF THOSE TILES.",
     "ae": ""}, {"price": "12", "name": "Food Factory", "tags": ["building"], "number": "41", "type": "Automated",
                 "text": "Decrease your plant production 1 step and increase your MC production 4 steps.", "ae": ""},
    {"price": "8", "name": "Forced Precipitation", "tags": ["venus"], "number": "226", "type": "Active", "text": "",
     "ae": "Action: Spend 2 MC to add a floater to this card, or spend 2 floaters here to increase Venus 1 step."},
    {"price": "14", "name": "Freyja Biodomes", "tags": ["plant", "venus"], "number": "227", "type": "Automated",
     "text": "Requires Venus 10%. Add 2 microbes or 2 animals TO ANOTHER VENUS CARD. Decrease your energy production 1 step, and increase your MC production by 2 steps.",
     "ae": ""}, {"price": "6", "name": "Fuel Factory", "tags": ["building"], "number": "180", "type": "Automated",
                 "text": "Decreases your energy production 1 step and increase your titanium and your MC production 1 step each.",
                 "ae": ""},
    {"price": "1", "name": "Fueled Generators", "tags": ["building", "energy"], "number": "100", "type": "Automated",
     "text": "Decrease your MC production 1 step and increase your energy production 1 step.", "ae": ""},
    {"price": "14", "name": "Fusion Power", "tags": ["science", "building", "energy"], "number": "132",
     "type": "Automated", "text": "Requires 2 power tags. Increase your energy production 3 steps.", "ae": ""},
    {"price": "15", "name": "Gaillean Waystation", "tags": ["space"], "number": "C13", "type": "Automated",
     "text": "Increase your MC production 1 step for every Jovian tags in play.", "ae": ""},
    {"price": "20", "name": "Ganymede Colony", "tags": ["space", "city", "jovian"], "number": "81", "type": "Automated",
     "text": "Place a city tile ON THE RESERVED AREA [for Ganymede Colony]. 1 VP per Jovian tag you have.", "ae": ""},
    {"price": "12", "name": "Gene Repair", "tags": ["science"], "number": "91", "type": "Automated",
     "text": "Requires 3 science tags. Increase your MC production 2 steps.", "ae": ""},
    {"price": "11", "name": "Geothermal Power", "tags": ["building", "energy"], "number": "117", "type": "Automated",
     "text": "Increase your energy production 2 steps.", "ae": ""},
    {"price": "11", "name": "GHG Factories", "tags": ["building"], "number": "126", "type": "Automated",
     "text": "Decrease your energy production 1 step and increase your heat production 4 steps.", "ae": ""},
    {"price": "23", "name": "GHG Import from Venus", "tags": ["space", "venus", "event"], "number": "228",
     "type": "Event", "text": "Raise Venus 1 step. Increase your heat production 3 steps.", "ae": ""},
    {"price": "8", "name": "GHG Producing Bacteria", "tags": ["science", "microbe"], "number": "34", "type": "Active",
     "text": "Requires 4% oxygen.",
     "ae": "Action: Add 1 microbe to this card, or remove 2 microbes to raise temperature 1 step."},
    {"price": "36", "name": "Giant Ice Asteroid", "tags": ["space", "event"], "number": "80", "type": "Event",
     "text": "Raise temperature 2 steps and place 2 ocean tiles. Remove up to 6 plants from any plyer.", "ae": ""},
    {"price": "27", "name": "Giant Solar Shade", "tags": ["space", "venus"], "number": "229", "type": "Automated",
     "text": "Raise Venus 3 steps.", "ae": ""},
    {"price": "17", "name": "Giant Space Mirror", "tags": ["space", "energy"], "number": "83", "type": "Automated",
     "text": "Increase your energy production 3 steps.", "ae": ""},
    {"price": "11", "name": "Grass", "tags": ["plant"], "number": "87", "type": "Automated",
     "text": "Requires -16\ufffdC or warmer. Increase your plant production 1 step. Gain 3 plants.", "ae": ""},
    {"price": "12", "name": "Great Dam", "tags": ["building", "energy"], "number": "136", "type": "Automated",
     "text": "Requires 4 ocean tiles. Increase your energy production 2 steps.", "ae": ""},
    {"price": "6", "name": "Great Escarpment Consortium", "tags": [], "number": "61", "type": "Automated",
     "text": "Requires that you have steel production. Decrease any steel production 1 step and increase your own 1 step",
     "ae": ""},
    {"price": "6", "name": "Greenhouses", "tags": ["building", "plant"], "number": "96", "type": "Automated",
     "text": "Gain 1 plant for each city tile in play.", "ae": ""},
    {"price": "20", "name": "Gyropolis", "tags": ["building", "city"], "number": "230", "type": "Automated",
     "text": "Decrease your energy production 2 steps. Increase your MC production 1 step for each Venus and Earth tag you have. Place a city tile.",
     "ae": ""}, {"price": "3", "name": "Hackers", "tags": [], "number": "125", "type": "Automated",
                 "text": "Decrease your energy production 1 step and any MC production 2 steps. Increase your MC production 2 steps.",
                 "ae": ""},
    {"price": "6", "name": "Heat Trappers", "tags": ["building", "energy"], "number": "178", "type": "Automated",
     "text": "Decrease any heat production 2 steps and increase your energy production 1 step.", "ae": ""},
    {"price": "6", "name": "Heather", "tags": ["plant"], "number": "88", "type": "Automated",
     "text": "Requires -14\ufffdC or warmer. Increase your plant production 1 step. Gain 1 plant.", "ae": ""},
    {"price": "3", "name": "Heavy Taxation", "tags": ["earth"], "number": "C14", "type": "Automated",
     "text": "Requires 2 Earth tags. Increase your MC production 2 steps, and gain 4 MC.", "ae": ""},
    {"price": "12", "name": "Herbivores", "tags": ["animal"], "number": "147", "type": "Active",
     "text": "Requires 8% oxygen. Add 1 animal to this card. Decrease any plant production 1 step. 1 VP per 2 animals on this card.",
     "ae": "Effect: When you place a greenery tile, add an animal to this card."},
    {"price": "1", "name": "Hired Raiders", "tags": ["event"], "number": "124", "type": "Event",
     "text": "Steal up to 2 steel, or 3MC from any player.", "ae": ""},
    {"price": "10", "name": "House Printing", "tags": ["building"], "number": "P36", "type": "Automated",
     "text": "Increase your steel production 1 step.", "ae": ""},
    {"price": "11", "name": "Hydrogen to Venus", "tags": ["space", "event"], "number": "231", "type": "Event",
     "text": "Raise Venus 1 step. Add 1 floater to A VENUS CARD for each Jovian tag you have.", "ae": ""},
    {"price": "23", "name": "Ice Asteroid", "tags": ["space", "event"], "number": "78", "type": "Event",
     "text": "Place 2 ocean tiles.", "ae": ""},
    {"price": "5", "name": "Ice cap Melting", "tags": ["event"], "number": "181", "type": "Event",
     "text": "Requires +2\ufffdC or warmer. Place 1 ocean tile.", "ae": ""},
    {"price": "23", "name": "Ice Moon Colony", "tags": ["space"], "number": "C15", "type": "Automated",
     "text": "Place 1 colony and 1 ocean tile.", "ae": ""},
    {"price": "13", "name": "Immigrant City", "tags": ["building", "city"], "number": "200", "type": "Active",
     "text": "Decrease your energy production 1 step and decrease your MC production 2 steps. Place a city tile.",
     "ae": "Effect: Each time a city tile is placed, including this, increase your MC production 1 step."},
    {"price": "31", "name": "Immigration Shuttles", "tags": ["space", "earth"], "number": "198", "type": "Automated",
     "text": "Increase your MC production 5 steps. 1 VP for every 3rd city in play.", "ae": ""},
    {"price": "11", "name": "Impactor Swarm", "tags": ["space", "event"], "number": "C16", "type": "Event",
     "text": "Requries 2 Jovian tags. Gain 12 heat. Remove up to 2 plants from any player.", "ae": ""},
    {"price": "9", "name": "Import of Advanced GHG", "tags": ["space", "earth", "event"], "number": "167",
     "type": "Event", "text": "Increase your heat production 2 steps.", "ae": ""},
    {"price": "7", "name": "Imported GHG", "tags": ["space", "earth", "event"], "number": "162", "type": "Event",
     "text": "Increase your heat production 1 step and gain 3 hear.", "ae": ""},
    {"price": "16", "name": "Imported Hydrogen", "tags": ["space", "earth", "event"], "number": "19", "type": "Event",
     "text": "Gain 3 plants, or add 3 microbes or 2 animals to ANOTHER card. Place an ocean tile.", "ae": ""},
    {"price": "23", "name": "Imported Nitrogen", "tags": ["space", "earth", "event"], "number": "163", "type": "Event",
     "text": "Raise your TR 1 step and gain 4 plants. Add 3 microbes to ANOTHER card and 2 animals to ANOTHER card.",
     "ae": ""}, {"price": "0", "name": "Indentured Workers", "tags": ["event"], "number": "195", "type": "Event",
                 "text": "The next card you play this generation costs 8MC less.", "ae": ""},
    {"price": "4", "name": "Industrial Center", "tags": ["building"], "number": "123", "type": "Active",
     "text": "Place [the Industrial Center] tile ADJACENT TO A CITY TILE.",
     "ae": "Action: Spend 7 MC to increase your steel production 1 step."},
    {"price": "12", "name": "Industrial Microbes", "tags": ["building", "microbe"], "number": "158",
     "type": "Automated", "text": "Increase your energy production and your steel production 1 step each.", "ae": ""},
    {"price": "9", "name": "Insects", "tags": ["microbe"], "number": "148", "type": "Automated",
     "text": "Requires 6% oxygen. Increase your plant production 1 step for each plant tag you have.", "ae": ""},
    {"price": "2", "name": "Insulation", "tags": [], "number": "152", "type": "Automated",
     "text": "Decrease your heat production any number of steps and increase your MC production the same number of steps.",
     "ae": ""},
    {"price": "12", "name": "Interplanetary Colony Ship", "tags": ["space", "earth", "event"], "number": "C17",
     "type": "Event", "text": "Place a colony.", "ae": ""},
    {"price": "24", "name": "Interstellar Colony Ship", "tags": ["space", "earth", "event"], "number": "27",
     "type": "Event", "text": "Requires 5 science tags.", "ae": ""},
    {"price": "2", "name": "Invention Contest", "tags": ["science", "event"], "number": "192", "type": "Event",
     "text": "Look at the top 3 cards from the deck. Take 1 of them into hand and discard the other 2", "ae": ""},
    {"price": "9", "name": "Inventors' Guild", "tags": ["science"], "number": "6", "type": "Active", "text": "",
     "ae": "Action: Look at the top card and either buy it or discard it"},
    {"price": "3", "name": "Investment Loan", "tags": ["earth", "event"], "number": "151", "type": "Event",
     "text": "Decrease your MC production 1 step. Gain 10 MC.", "ae": ""},
    {"price": "41", "name": "Io Mining Industries", "tags": ["space", "jovian"], "number": "92", "type": "Automated",
     "text": "Increase your titanium production 2 steps and your MC production 2 steps. 1 VP per Jovian tag you have.",
     "ae": ""},
    {"price": "17", "name": "Io Sulphur Research", "tags": ["science", "jovian"], "number": "232", "type": "Automated",
     "text": "Draw 1 card, or draw 3 cards if you have at least 3 Venus tags.", "ae": ""},
    {"price": "11", "name": "Ironworks", "tags": ["building"], "number": "101", "type": "Active", "text": "",
     "ae": "Action: Spend 4 energy to gain 1 steel and increase oxygen 1 step."},
    {"price": "5", "name": "Ishtar Mining", "tags": ["venus"], "number": "233", "type": "Automated",
     "text": "Requires Venus 8%. Increase your titanium production 1 step.", "ae": ""},
    {"price": "12", "name": "Jet Stream Microscrappers", "tags": ["venus"], "number": "234", "type": "Active",
     "text": "",
     "ae": "Action: Spend 1 titanium to add 2 floaters to this card, or remove 2 floaters here to raise Venus 1 step."},
    {"price": "20", "name": "Jovian Lanterns", "tags": ["jovian"], "number": "C18", "type": "Active",
     "text": "Requires 1 Jovian tag. Increase your TR 1 step. Add 2 floaters to ANY card. 1 VP per 2 floaters here.",
     "ae": "Action: Spend 1 titanium to add 2 floaters here."},
    {"price": "9", "name": "Jupiter Floating Station", "tags": ["jovian"], "number": "C19", "type": "Active",
     "text": "Requires 3 science tags.",
     "ae": "Action: Add 1 floater to a JOVIAN CARD, or gain 1 MC for every floater here (Max 4)."},
    {"price": "17", "name": "Kelp Farming", "tags": [], "number": "55", "type": "Automated",
     "text": "Requires 6 ocean tiles. Increase your MC production 2 steps and your plant production 3 steps. Gain 2 plants.",
     "ae": ""},
    {"price": "9", "name": "Lagrange Observatory", "tags": ["science", "space"], "number": "196", "type": "Automated",
     "text": "Draw 1 card.", "ae": ""},
    {"price": "18", "name": "Lake Marineris", "tags": [], "number": "53", "type": "Automated",
     "text": "Requires 0\ufffdC or warmer. Place 2 ocean tiles.", "ae": ""},
    {"price": "1", "name": "Land Claim", "tags": ["event"], "number": "66", "type": "Event",
     "text": "Place your marker on a non-reserved area. Only you may place a tile here", "ae": ""},
    {"price": "36", "name": "Large Convoy", "tags": ["space", "earth", "event"], "number": "143", "type": "Event",
     "text": "Place an ocean tile and draw 2 cards. Gain 5 plants, or add 4 animals to ANOTHER card.", "ae": ""},
    {"price": "18", "name": "Lava Flows", "tags": ["event"], "number": "140", "type": "Event",
     "text": "Raise the temperature 2 steps and place this [the Lava Flow] tile ON EITHER THARSIS THOLUS, ASCRAEUS MONS, PAVONIS MONS OR ARSIA MONS.",
     "ae": ""},
    {"price": "15", "name": "Lava Tube Settlement", "tags": ["building", "city"], "number": "P37", "type": "Automated",
     "text": "Decrease your energy production 1 step. Increase your MC production 2 steps. Place a city tile ON A VOLCANIC AREA, same as Lava Flows, regardless of adjacent cities.",
     "ae": ""}, {"price": "7", "name": "Lichen", "tags": ["plant"], "number": "159", "type": "Automated",
                 "text": "Requires -24\ufffdC or warmer. Increase your plant production 1 step.", "ae": ""},
    {"price": "8", "name": "Lightning Harvest", "tags": ["energy"], "number": "46", "type": "Automated",
     "text": "Requires 3 science tags. Increase your energy production and your MC production 1 step each.", "ae": ""},
    {"price": "13", "name": "Livestock", "tags": ["animal"], "number": "184", "type": "Active",
     "text": "Requires 9% oxygen. Decrease your plant production 1 step and increase your MC production 2 steps. 1 VP for each animal on this card.",
     "ae": "Action: Add 1 animal to this card."},
    {"price": "1", "name": "Local Heat Trapping", "tags": ["event"], "number": "190", "type": "Event",
     "text": "Spend 5 heat to either gain 4 plants, or to add 2 animals to ANOTHER card.", "ae": ""},
    {"price": "4", "name": "Local Shading", "tags": ["venus"], "number": "235", "type": "Active", "text": "",
     "ae": "Action: Add 1 floater to this card, or spend 1 floater here to raise your MC production 1 step."},
    {"price": "4", "name": "Luna Governor", "tags": ["earth", "earth"], "number": "C20", "type": "Automated",
     "text": "Requires 3 Earch tags. Increase your MC production 2 steps.", "ae": ""},
    {"price": "21", "name": "Luna Metropolis", "tags": ["space", "city", "earth"], "number": "236", "type": "Automated",
     "text": "Increase your MC production 1 step for each Earth tag you have, including this. Place a city tile ON THE RESERVED AREA.",
     "ae": ""}, {"price": "13", "name": "Lunar Beam", "tags": ["earth", "energy"], "number": "30", "type": "Automated",
                 "text": "Decrease your MC production 2 steps and increase your heat production and energy production 2 steps each.",
                 "ae": ""},
    {"price": "19", "name": "Lunar Exports", "tags": ["space", "earth"], "number": "C21", "type": "Automated",
     "text": "Increase your plant production 2 steps, or increase your MC production 5 steps.", "ae": ""},
    {"price": "11", "name": "Lunar Mining", "tags": ["earth"], "number": "C22", "type": "Automated",
     "text": "Increase your titanium production. 1 step for every 2 Earth tags you have in play, including this.",
     "ae": ""}, {"price": "8", "name": "Luxury Foods", "tags": [], "number": "237", "type": "Automated",
                 "text": "Requires Venus, Earth and Jovian tags.", "ae": ""},
    {"price": "5", "name": "Magnetic Field Dome", "tags": ["building"], "number": "171", "type": "Automated",
     "text": "Decrease your energy production 2 steps and increase your plant production 1 step. Raise your terraform rating 1 step.",
     "ae": ""},
    {"price": "20", "name": "Magnetic Field Generators", "tags": ["building"], "number": "165", "type": "Automated",
     "text": "Decrease your energy production 4 steps and increase your plant production 2 steps. Raise your TR 3 steps.",
     "ae": ""}, {"price": "12", "name": "Mangrove", "tags": ["plant"], "number": "59", "type": "Automated",
                 "text": "Requires +4\ufffdC or warmer. Place a Greenery tile ON AN AREA RESERVED FOR OCEAN and raise oxygen 1 step. Disregard normal placement restrictions for this.",
                 "ae": ""},
    {"price": "1", "name": "Market Manipulation", "tags": ["earth", "event"], "number": "C23", "type": "Event",
     "text": "Increase one colony tile track 1 step. Decrease another colony tile track 1 step", "ae": ""},
    {"price": "8", "name": "Mars University", "tags": ["science", "building"], "number": "73", "type": "Active",
     "text": "",
     "ae": "Effect: When you play a science tag, including this, you may discard a card from hand to draw a card."},
    {"price": "13", "name": "Martian Rails", "tags": ["building"], "number": "7", "type": "Active", "text": "",
     "ae": "Action: Spend 1 energy to gain 1 MC for each city tile ON MARS."},
    {"price": "9", "name": "Martian Survey", "tags": ["science", "event"], "number": "P38", "type": "Event",
     "text": "Oxygen must be 4% or lower. Draw 2 cards.", "ae": ""},
    {"price": "12", "name": "Martian Zoo", "tags": ["building", "animal"], "number": "C24", "type": "Active",
     "text": "Requires 2 city tiles in play.",
     "ae": "Effect: when you play an Earth tag, place an animal here. Action: Gain 1 MC per animal here."},
    {"price": "8", "name": "Mass Converter", "tags": ["science", "energy"], "number": "94", "type": "Active",
     "text": "Requires 5 science tags. Increase your energy production 6 steps.",
     "ae": "Effect: When you play a space card, you pay 2 MC less for it."},
    {"price": "18", "name": "Maxwell Base", "tags": ["city", "venus"], "number": "238", "type": "Active",
     "text": "Requires Venus 12%. Decrease your energy production 1 step. Place a city tile ON THE RESERVED AREA.",
     "ae": "Action: Add 1 resource to ANOTEHR VENUS CARD."},
    {"price": "8", "name": "Media Archives", "tags": ["earth"], "number": "107", "type": "Automated",
     "text": "Gain 1 MC for each event EVER PLAYED by all players", "ae": ""},
    {"price": "6", "name": "Media Group", "tags": ["earth"], "number": "109", "type": "Active", "text": "",
     "ae": "Effect: After you play an event card, you gain 3MC"},
    {"price": "13", "name": "Medical Lab", "tags": ["science", "building"], "number": "207", "type": "Automated",
     "text": "Increase your MC production 1 step for every 2 building tags you have, including this.", "ae": ""},
    {"price": "28", "name": "Methane From Titan", "tags": ["space", "jovian"], "number": "18", "type": "Automated",
     "text": "Requires 2% oxygen. Increase your heat production 2 steps and your plant production 2 steps.", "ae": ""},
    {"price": "3", "name": "Micro-Mills", "tags": [], "number": "164", "type": "Automated",
     "text": "Increase your heat production 1 step.", "ae": ""},
    {"price": "4", "name": "Mine", "tags": ["building"], "number": "56", "type": "Automated",
     "text": "Increase your steel production 1 step.", "ae": ""},
    {"price": "5", "name": "Mineral Deposit", "tags": ["event"], "number": "62", "type": "Event",
     "text": "Gain 5 steel.", "ae": ""},
    {"price": "4", "name": "Mining Area", "tags": ["building"], "number": "64", "type": "Automated",
     "text": "Place [the mining] tile on an area with a steel or titanium placement bonus, adjacent to another of your tiles. Increase your production of that resource 1 step.",
     "ae": ""}, {"price": "20", "name": "Mining Colony", "tags": ["space"], "number": "C25", "type": "Automated",
                 "text": "Increase your titanium production 1 step. Place a colony.", "ae": ""},
    {"price": "12", "name": "Mining Expedition", "tags": ["event"], "number": "63", "type": "Event",
     "text": "Raise oxygen 1 step. Remove 2 plants from any player. Gain 2 steel.", "ae": ""},
    {"price": "5", "name": "Mining Quota", "tags": ["building"], "number": "239", "type": "Automated",
     "text": "Requires Venus, Earth and Jovian tags. Increase your steel production 2 steps.", "ae": ""},
    {"price": "9", "name": "Mining Rights", "tags": ["building"], "number": "67", "type": "Automated",
     "text": "Place [the mining] tile on an area with a steel or titanium placement bonus. Increase that production 1 step.",
     "ae": ""}, {"price": "5", "name": "Minority Refuge", "tags": ["space"], "number": "C26", "type": "Automated",
                 "text": "Decrese your MC production 2 steps. Place a colony.", "ae": ""},
    {"price": "12", "name": "Miranda Resort", "tags": ["space", "jovian"], "number": "51", "type": "Automated",
     "text": "Increase your MC production 1 step for each Earth tag you have.", "ae": ""},
    {"price": "20", "name": "Mohole Area", "tags": ["building"], "number": "142", "type": "Automated",
     "text": "Increase your heat production 4 steps. Place [the Mohole Area] tile ON AN AREA RESERVED FOR OCEAN.",
     "ae": ""}, {"price": "11", "name": "Molecular Printing", "tags": ["science"], "number": "C27", "type": "Automated",
                 "text": "Gain 1 MC fo each city tile in play. Gain 1 MC for each colony in play.", "ae": ""},
    {"price": "4", "name": "Moss", "tags": ["plant"], "number": "122", "type": "Automated",
     "text": "Requires 3 ocean tiles and that you lose 1 plant. Increase your plant production 1 step.", "ae": ""},
    {"price": "9", "name": "Natural Preserve", "tags": ["science", "building"], "number": "44", "type": "Automated",
     "text": "Oxygen must be 4% or less. Place this tile NEXT TO NO OTHER TILE. Increase your MC production 1 step.",
     "ae": ""}, {"price": "7", "name": "Neutralizer Factory", "tags": ["venus"], "number": "240", "type": "Automated",
                 "text": "Requires Venus 10%. Increase Venus 1 step.", "ae": ""},
    {"price": "11", "name": "Nitrite Reducing Bacteria", "tags": ["microbe"], "number": "157", "type": "Active",
     "text": "Add 3 microbes to this card.",
     "ae": "Action: Add 1 microbe to this card, or remove 3 microbes to increase your TR 1 step."},
    {"price": "25", "name": "Nitrogen from Titan", "tags": ["space", "jovian"], "number": "C28", "type": "Automated",
     "text": "Raise your TR 2 steps. Add 2 floaters to a JOVIAN CARD.", "ae": ""},
    {"price": "31", "name": "Nitrogen-Rich Asteroid", "tags": ["space", "event"], "number": "37", "type": "Event",
     "text": "Raise your terraforming rating 2 steps and temperature 1 step. Increase your plant production 1 step, or 4 steps if you have 3 plant tags.",
     "ae": ""}, {"price": "8", "name": "Nitrophilic Moss", "tags": ["plant"], "number": "146", "type": "Automated",
                 "text": "Requires 3 ocean tiles and that you lose 2 plants. Increase your plant production 2 steps.",
                 "ae": ""},
    {"price": "18", "name": "Noctis City", "tags": ["building", "city"], "number": "17", "type": "Automated",
     "text": "Decrease your energy production 1 step and increase your MC production 3 steps. Place a tile ON THE RESERVED AREA, disregarding normal placement restrictions.",
     "ae": ""},
    {"price": "10", "name": "Noctis Farming", "tags": ["building", "plant"], "number": "176", "type": "Automated",
     "text": "Requires -20\ufffdC or warmer. Increase your MC production 1 step and gain 2 plants.", "ae": ""},
    {"price": "10", "name": "Nuclear Power", "tags": ["building", "energy"], "number": "45", "type": "Automated",
     "text": "Decrease your MC production 2 steps and increase your energy production 3 steps.", "ae": ""},
    {"price": "10", "name": "Nuclear Zone", "tags": ["earth"], "number": "97", "type": "Automated",
     "text": "Place [the nuclear zone] tile and raise the temperature 2 steps.", "ae": ""},
    {"price": "10", "name": "Olympus Conference", "tags": ["science", "building", "earth"], "number": "185",
     "type": "Active", "text": "",
     "ae": "Effect: When you play a science tag, including this, either add a science resource to this card, or remove a science resource from this card to draw a card."},
    {"price": "11", "name": "Omnicourt", "tags": ["building"], "number": "241", "type": "Automated",
     "text": "Requires Venus, Earth, and Jovian tags. Increase your TR 2 steps.", "ae": ""},
    {"price": "23", "name": "Open City", "tags": ["building", "city"], "number": "108", "type": "Automated",
     "text": "Requires 12% oxygen. Decrease your energy production 1 step and increase your MC production 4 steps. Gain 2 plants and place a city tile.",
     "ae": ""},
    {"price": "7", "name": "Optimal Aerobraking", "tags": ["space"], "number": "31", "type": "Active", "text": "",
     "ae": "Effect: When you place a space event, you gain 3 MC and 3 heat."},
    {"price": "26", "name": "Orbital Reflectors", "tags": ["space", "venus"], "number": "242", "type": "Automated",
     "text": "Raise Venus 2 steps. Increase your heat production 2 steps.", "ae": ""},
    {"price": "13", "name": "Ore Processor", "tags": ["building"], "number": "104", "type": "Active", "text": "",
     "ae": "Action: Spend 4 energy to gain 1 titanium and increase oxygen 1 step."},
    {"price": "7", "name": "Penguins", "tags": ["animal"], "number": "212", "type": "Active",
     "text": "Requires 8 Oceans. 1 VP per animal on this card.", "ae": "Action: Add 1 animal to this card."},
    {"price": "8", "name": "Permafrost extraction", "tags": ["event"], "number": "191", "type": "Event",
     "text": "Requires -8\ufffdC or warmer. Place 1 ocean tile.", "ae": ""},
    {"price": "7", "name": "Peroxide Power", "tags": ["building", "energy"], "number": "89", "type": "Automated",
     "text": "Decrease your MC production 1 step and increase your energy production 2 steps.", "ae": ""},
    {"price": "10", "name": "Pets", "tags": ["animal", "earth"], "number": "172", "type": "Active",
     "text": "Add 1 animal to this card. 1 VP per 2 animals here.",
     "ae": "Effect: When any city tile is placed, add an animal to this card. Animals may not be removed from this card."},
    {"price": "25", "name": "Phobos Space Haven", "tags": ["space", "city"], "number": "21", "type": "Automated",
     "text": "Increase your titanium production 1 step and place a city tile ON THE RESERVED AREA.", "ae": ""},
    {"price": "12", "name": "Physics Complex", "tags": ["science", "building"], "number": "95", "type": "Active",
     "text": "2 VP for each science resource on this card.",
     "ae": "Action: Spend 6 energy to add a science resource to this card."},
    {"price": "13", "name": "Pioneer Settlement", "tags": ["space"], "number": "C29", "type": "Automated",
     "text": "Requires that you have no more than 1 colony. Decrease your MC production 2 steps. Place a colony.",
     "ae": ""}, {"price": "15", "name": "Plantation", "tags": ["plant"], "number": "193", "type": "Automated",
                 "text": "Requires 2 science tags. Place a greenery tile and raise oxygen 1 step.", "ae": ""},
    {"price": "18", "name": "Power Grid", "tags": ["energy"], "number": "102", "type": "Automated",
     "text": "Increase your energy production 1 step for each power tag you have, including this.)", "ae": ""},
    {"price": "4", "name": "Power Infrastructure", "tags": ["building", "energy"], "number": "194", "type": "Active",
     "text": "", "ae": "Action: Spend any amount of energy to gain that amount of MC."},
    {"price": "4", "name": "Power Plant", "tags": ["building", "energy"], "number": "141", "type": "Automated",
     "text": "Increase your energy production 1 step.", "ae": ""},
    {"price": "5", "name": "Power Supply Consortium", "tags": ["energy"], "number": "160", "type": "Automated",
     "text": "Requires 2 power tags. Decrease any energy production 1 step and increase your own 1 step.", "ae": ""},
    {"price": "14", "name": "Predators", "tags": ["animal"], "number": "24", "type": "Active",
     "text": "Requires 11% oxygen. 1 VP per animal on this card.",
     "ae": "Action: Remove 1 animal from any card and add it to this card."},
    {"price": "0", "name": "Productive Outpost", "tags": [], "number": "C30", "type": "Automated",
     "text": "Gain all your colony bonuses", "ae": ""},
    {"price": "5", "name": "Protected Habitats", "tags": [], "number": "173", "type": "Active", "text": "",
     "ae": "[Effect: ]Opponents may not remove your [plants, animals or microbes]"},
    {"price": "23", "name": "Protected Valley", "tags": ["building", "plant"], "number": "174", "type": "Automated",
     "text": "Increase your MC production 2 steps. Place a greenery tile ON AN AREA RESERVED FOR OCEAN, disregarding normal placement restrictions, and increase oxygen 1 step.",
     "ae": ""}, {"price": "2", "name": "Psychrophiles", "tags": ["microbe"], "number": "P39", "type": "Active",
                 "text": "Requires temperature -20\ufffdC or colder.",
                 "ae": "Action: Add a microbe to this card. Effect: When paying for a plant card, microbes here may be used as 2 MC each."},
    {"price": "8", "name": "Quantum Communications", "tags": [], "number": "C31", "type": "Automated",
     "text": "Requires 4 science tags. Increase your MC production 1 step for each colony in play.", "ae": ""},
    {"price": "13", "name": "Quantum Extractor", "tags": ["science", "energy"], "number": "79", "type": "Active",
     "text": "", "ae": "Effect: When you play a space card, you pay 2 MC less for it"},
    {"price": "8", "name": "Rad-Chem Factory", "tags": ["building"], "number": "205", "type": "Automated",
     "text": "Decrease your energy production 1 step. Raise your terraform rating 2 steps.", "ae": ""},
    {"price": "6", "name": "Rad-Suits", "tags": [], "number": "186", "type": "Automated",
     "text": "Requires 2 cities in play. Increase your MC production 1 step.", "ae": ""},
    {"price": "17", "name": "Red Spot Observatory", "tags": ["science", "jovian"], "number": "C32", "type": "Active",
     "text": "Requires 3 science tags. Draw 2 cards.",
     "ae": "Action: Add 1 floater to this card, or spend 1 floater here to draw a card."},
    {"price": "10", "name": "Refugee Camps", "tags": ["earth"], "number": "C33", "type": "Active",
     "text": "1 VP for each camp resource on this card.",
     "ae": "Action: Decrease your MC production 1 step to add a camp resource to this card."},
    {"price": "13", "name": "Regolith Eaters", "tags": ["science", "microbe"], "number": "33", "type": "Active",
     "text": "",
     "ae": "Action: Add 1 microbe to this card, or remove 2 microbe from this card to raise oxygen level 1 step."},
    {"price": "14", "name": "Release of Inert Gases", "tags": ["event"], "number": "36", "type": "Event",
     "text": "Raise your terraform rating 2 steps.", "ae": ""},
    {"price": "11", "name": "Research", "tags": ["science", "science"], "number": "90", "type": "Automated",
     "text": "Counts as playing 2 science cards. Draw 2 cards.", "ae": ""},
    {"price": "20", "name": "Research Colony", "tags": ["science", "space"], "number": "C34", "type": "Automated",
     "text": "Place a colony. MAY BE PLACED WHERE YOU ALREADY HAVE A COLONY. Draw 2 cards.", "ae": ""},
    {"price": "4", "name": "Research Coordination", "tags": [], "number": "P40", "type": "Automated",
     "text": "After being played, when you perform an action, the wild tag counts as any tag of your choice.",
     "ae": ""}, {"price": "18", "name": "Research Outpost", "tags": ["science", "building", "city"], "number": "20",
                 "type": "Active", "text": "Place a city tile NEXT TO NO OTHER TILE.",
                 "ae": "Effect: When you play a card, you pay 1 MC less for it."},
    {"price": "11", "name": "Restricted Area", "tags": ["science"], "number": "199", "type": "Active",
     "text": "Place [the restricted area] tile.", "ae": "Action: Spend 2MC to draw a card."},
    {"price": "4", "name": "Rim Freighters", "tags": ["space"], "number": "C35", "type": "Active", "text": "",
     "ae": "Effect: When you trade, you pay 1 less resource for it."},
    {"price": "9", "name": "Robotic Workforce", "tags": ["science"], "number": "86", "type": "Automated",
     "text": "Duplicate only the production box of one of your building cards.", "ae": ""},
    {"price": "6", "name": "Rotator Impacts", "tags": ["space"], "number": "243", "type": "Active",
     "text": "Venus must be 14% or lower.",
     "ae": "Action: Spend 6 MC to add an asteroid resource to this card (TITANIUM MAY BE USED), or spend 1 resource from this card to increase VENUS 1 step."},
    {"price": "8", "name": "Rover Construction", "tags": ["building"], "number": "38", "type": "Active", "text": "",
     "ae": "Effect: When any city tile is placed, gain 2 MC"},
    {"price": "1", "name": "Sabotage", "tags": ["event"], "number": "121", "type": "Event",
     "text": "Remove up to 3 titanium from any player, or 4 steel, or 7 MC.", "ae": ""},
    {"price": "10", "name": "Satellites", "tags": ["space"], "number": "175", "type": "Automated",
     "text": "Increase your MC production 1 step for each space tag you have, including this one.", "ae": ""},
    {"price": "3", "name": "Search For Life", "tags": ["science"], "number": "5", "type": "Active",
     "text": "Oxygen must be 6% or less. 3 VPs if you have one or more science resource here.",
     "ae": "Action: Spend 1 MC to reveal and discard the top card of the draw deck. If that card has a microbe tag, add a science resource here."},
    {"price": "12", "name": "Security Fleet", "tags": ["space"], "number": "28", "type": "Active",
     "text": "1 VP for each fighter resource on this card.",
     "ae": "Action: Spend 1 titanium to add 1 fighter resource to this card."},
    {"price": "7", "name": "Self-Replicating Robots", "tags": [], "number": "210", "type": "Active",
     "text": "Requires 2 science tags.",
     "ae": "Action: Reveal and place a SPACE OR BUILDING card here from hand, and place 2 resources on it, OR double the resources on a card here. Effect: Cards here may be played as if from hand with its cost reduced by the number of resources on it."},
    {"price": "7", "name": "SF Memorial", "tags": ["building"], "number": "P41", "type": "Automated",
     "text": "Draw 1 card.", "ae": ""},
    {"price": "10", "name": "Shuttles", "tags": ["space"], "number": "166", "type": "Active",
     "text": "Requires 5% oxygen. Decrease your energy production 1 step and increase your MC production 2 steps.",
     "ae": "Effect: When you play a space card, you pay 2MC less for it."},
    {"price": "7", "name": "Sister Planet Support", "tags": ["earth", "venus"], "number": "244", "type": "Automated",
     "text": "Requires Venus and Earth tag. Increase your MC production 3 steps.", "ae": ""},
    {"price": "18", "name": "Sky Docks", "tags": ["space", "earth"], "number": "C36", "type": "Active",
     "text": "Requires 2 Earth tags. Gain 1 Trade Fleet.",
     "ae": "Effect: When you play a card, you pay 1 MC less for it."},
    {"price": "6", "name": "Small Animals", "tags": ["animal"], "number": "54", "type": "Active",
     "text": "Requires 6% oxygen. Decrease any plant production 1 step. 1 VP per 2 animals on this card.",
     "ae": "Action: Add 1 animal to this card."},
    {"price": "10", "name": "Small Asteroid", "tags": ["space", "event"], "number": "209", "type": "Event",
     "text": "Terraforming Mars Promo. Increase temperature 1 step. Remove up to 2 plants from any player.", "ae": ""},
    {"price": "12", "name": "Snow Algae", "tags": ["plant"], "number": "211", "type": "Active",
     "text": "Requires 2 oceans. Increase your plant production and your heat production 1 step each.", "ae": ""},
    {"price": "9", "name": "Soil Factory", "tags": ["building"], "number": "179", "type": "Automated",
     "text": "Decrease your energy production 1 step and increase your plant production 1 step.", "ae": ""},
    {"price": "11", "name": "Solar Power", "tags": ["building", "energy"], "number": "113", "type": "Automated",
     "text": "Increase your energy production 1 step.", "ae": ""},
    {"price": "9", "name": "Solar Probe", "tags": ["science", "space", "event"], "number": "C37", "type": "Event",
     "text": "Draw 1 card for every 3 science tags you have, including this.", "ae": ""},
    {"price": "23", "name": "Solar Reflectors", "tags": ["space"], "number": "C38", "type": "Automated",
     "text": "Increase your heat production 5 steps.", "ae": ""},
    {"price": "11", "name": "Solar Wind Power", "tags": ["science", "space", "energy"], "number": "77",
     "type": "Automated", "text": "Increase your energy production 1 step and gain 2 titanium.", "ae": ""},
    {"price": "7", "name": "Solarnet", "tags": [], "number": "245", "type": "Automated",
     "text": "Requires Venus, Earth, and Jovian tags. Draw 2 cards.", "ae": ""},
    {"price": "35", "name": "Soletta", "tags": ["space"], "number": "203", "type": "Automated",
     "text": "Increase your heat production 7 steps.", "ae": ""},
    {"price": "27", "name": "Space Elevator", "tags": ["building", "space"], "number": "13", "type": "Active",
     "text": "Increase your titanium production 1 step.", "ae": "Action: Spend 1 steel to gain 5 MC"},
    {"price": "12", "name": "Space Hotels", "tags": ["space", "earth"], "number": "P42", "type": "Automated",
     "text": "Requires 2 Earth tags. Increase your MC production 4 steps.", "ae": ""},
    {"price": "3", "name": "Space Mirrors", "tags": ["space", "energy"], "number": "76", "type": "Active", "text": "",
     "ae": "Action: Spend 7MC to increase your energy production 1 step."},
    {"price": "22", "name": "Space Port", "tags": ["building", "city"], "number": "C39", "type": "Automated",
     "text": "Requires 1 colony. Gain 1 Trade Fleet. Place a city tile. Decrease your energy production 1 step, and increase your MC production 4 steps.",
     "ae": ""}, {"price": "27", "name": "Space Port Colony", "tags": ["space"], "number": "C40", "type": "Automated",
                 "text": "Requires a colony. Place a colony. MAY BE PLACED ON A COLONY TILE WHERE YOU ALREADY HAVE A COLONY. Gain 1 Trade Fleet. 1 VP per 2 colonies in play.",
                 "ae": ""},
    {"price": "10", "name": "Space Station", "tags": ["space"], "number": "25", "type": "Active", "text": "",
     "ae": "Effect: When you play a space card, you pay 2 MC less for it."},
    {"price": "4", "name": "Special Design", "tags": ["science", "event"], "number": "206", "type": "Event",
     "text": "The next card you play this generation is +2 or -2 in global requirements, your choice.", "ae": ""},
    {"price": "16", "name": "Spin-Inducing Asteroid", "tags": ["space", "event"], "number": "246", "type": "Event",
     "text": "Venus must be 10% or lower. Raise Venus 2 steps.", "ae": ""},
    {"price": "10", "name": "Spin-Off Department", "tags": ["building"], "number": "C41", "type": "Active",
     "text": "Increase your MC production 2 steps.",
     "ae": "Effect: WHEN PLAYING A CARD WITH A BASIC COST OF 20 MC OR MORE, draw a card"},
    {"price": "9", "name": "Sponsored Academies", "tags": ["science", "earth"], "number": "247", "type": "Automated",
     "text": "Discard 1 card from hand and THEN draw 3 cards. All OPPONENTS draw 1 card.", "ae": ""},
    {"price": "6", "name": "Sponsors", "tags": ["earth"], "number": "68", "type": "Automated",
     "text": "Increase your MC production 2 steps.", "ae": ""},
    {"price": "6", "name": "Standard Technology", "tags": ["science"], "number": "156", "type": "Active", "text": "",
     "ae": "Effect: After you pay for a standard project, except selling patents, you gain 3 MC."},
    {"price": "15", "name": "Steelworks", "tags": ["building"], "number": "103", "type": "Active", "text": "",
     "ae": "Action: Spend 4 energy to gain 2 steel and increase oxygen 1 step."},
    {"price": "22", "name": "Stratopolis", "tags": ["city", "venus"], "number": "248", "type": "Active",
     "text": "Requires 2 science tags. Increase your MC production 2 steps. Place a city tile on THE RESERVED AREA. 1 VP per 3 floaters on this card.",
     "ae": "Action: Add 2 floaters to ANY VENUS CARD."},
    {"price": "12", "name": "Stratospheric Birds", "tags": ["animal", "venus"], "number": "249", "type": "Active",
     "text": "Requires Venus 12%, and that you spend 1 floater from any card. 1 VP for each animal on this card.",
     "ae": "Action: Add 1 animal to this card."},
    {"price": "25", "name": "Strip Mine", "tags": ["building"], "number": "138", "type": "Automated",
     "text": "Decrease your energy production 2 steps. Increase your steel production 2 steps and your titanium production 1 step. Raise oxygen 2 steps.",
     "ae": ""}, {"price": "5", "name": "Sub-Zero Salt Fish", "tags": ["animal"], "number": "C42", "type": "Active",
                 "text": "Requires -6\ufffdC or warmer. Decrease any plant production 1 step. 1 VP per 2 animals on this card.",
                 "ae": "Action: Add 1 animal to this card."},
    {"price": "11", "name": "Subterranean Reservoir", "tags": ["event"], "number": "127", "type": "Event",
     "text": "Place 1 ocean tile.", "ae": ""},
    {"price": "21", "name": "Sulphur Exports", "tags": ["space", "venus"], "number": "250", "type": "Automated",
     "text": "Increase Venus 1 step. Increase your MC production 1 step for each Venus tag you have, including this.",
     "ae": ""},
    {"price": "6", "name": "Sulphur-Eating Bacteria", "tags": ["microbe", "venus"], "number": "251", "type": "Active",
     "text": "Requires Venus 6%.",
     "ae": "Action: Add 1 microbe to this card, or spend any number of microbes here to gain the triple amount of MC."},
    {"price": "4", "name": "Symbiotic Fungus", "tags": ["microbe"], "number": "133", "type": "Active",
     "text": "Requires -14\ufffdC or warmer.", "ae": "Action: Add a microbe to ANOTHER card."},
    {"price": "4", "name": "Tardigrades", "tags": ["microbe"], "number": "49", "type": "Active",
     "text": "1 VP per 4 microbes on this card.", "ae": "Action: Add 1 microbe to this card."},
    {"price": "5", "name": "Technology Demonstration", "tags": ["science", "space", "event"], "number": "204",
     "type": "Event", "text": "Draw 2 cards.", "ae": ""},
    {"price": "18", "name": "Tectonic Stress Power", "tags": ["building", "energy"], "number": "145",
     "type": "Automated", "text": "Requires 2 science tags. Increase your energy production 3 steps.", "ae": ""},
    {"price": "8", "name": "Terraforming Contract", "tags": ["earth"], "number": "252", "type": "Automated",
     "text": "Requires that you have at least 25 TR. Increase your MC production 4 steps.", "ae": ""},
    {"price": "33", "name": "Terraforming Ganymede", "tags": ["space", "jovian"], "number": "197", "type": "Automated",
     "text": "Raise your TR 1 step for each Jovian tag you have, including this.", "ae": ""},
    {"price": "9", "name": "Thermophiles", "tags": ["microbe", "venus"], "number": "253", "type": "Active",
     "text": "Requires Venus 6%.",
     "ae": "Action: Add 1 microbe to ANY VENUS CARD, or spend 2 microbes here to raise Venus 1 step."},
    {"price": "21", "name": "Titan Air-Scrapping", "tags": ["jovian"], "number": "C43", "type": "Active", "text": "",
     "ae": "Action: Spend 1 titanium to add 2 floaters to this card, or spend 2 floaters here to increase your TR 1 step."},
    {"price": "18", "name": "Titan Floating Launch-Pad", "tags": ["jovian"], "number": "C44", "type": "Active",
     "text": "Add 2 foaters to ANY JOVIAN CARD.",
     "ae": "Action: Add 1 floater to ANY JOVIAN CARD, or spend 1 floater here to trade for free"},
    {"price": "23", "name": "Titan Shuttles", "tags": ["space", "jovian"], "number": "C45", "type": "Active",
     "text": "",
     "ae": "Action: Add 2 floaters to ANY JOVIAN CARD, or spend any number of floaters here to gain the same number of titanium."},
    {"price": "7", "name": "Titanium Mine", "tags": ["building"], "number": "144", "type": "Automated",
     "text": "Increase your titanium production 1 step.", "ae": ""},
    {"price": "12", "name": "Toll Station", "tags": ["space"], "number": "99", "type": "Automated",
     "text": "Increase your MC production 1 step for each space tag your OPPONENTS have.", "ae": ""},
    {"price": "23", "name": "Towing a Comet", "tags": ["space", "event"], "number": "75", "type": "Event",
     "text": "Gain 2 plants. Raise oxygen level 1 step and place an ocean tile.", "ae": ""},
    {"price": "6", "name": "Trade Envoys", "tags": [], "number": "C46", "type": "Active", "text": "",
     "ae": "Effect: When you trade, you may first increase that Colony Tile track 1 step."},
    {"price": "18", "name": "Trading Colony", "tags": ["space"], "number": "C47", "type": "Active",
     "text": "Place a colony.", "ae": "Effect: When you trade, you may first increase that Colony Tile track 1 step."},
    {"price": "6", "name": "Trans-Neptune Probe", "tags": ["science", "space"], "number": "84", "type": "Automated",
     "text": "", "ae": ""}, {"price": "13", "name": "Trees", "tags": ["plant"], "number": "60", "type": "Automated",
                             "text": "Requires -4\ufffdC or warmer. Increase your plant production 3 steps. Gain 1 plant.",
                             "ae": ""},
    {"price": "13", "name": "Tropical Resort", "tags": ["building"], "number": "98", "type": "Automated",
     "text": "Decrease your heat production 2 steps and increase your MC production 3 steps.", "ae": ""},
    {"price": "16", "name": "Tundra Farming", "tags": ["plant"], "number": "169", "type": "Automated",
     "text": "Requires -6\ufffdC or warmer. Increase your plant production 1 step and your MC production 2 steps. Gain 1 plant.",
     "ae": ""},
    {"price": "18", "name": "Underground City", "tags": ["building", "city"], "number": "32", "type": "Automated",
     "text": "Place a city tile. Decrease your energy production 2 steps and increase your steel production 2 steps.",
     "ae": ""},
    {"price": "6", "name": "Underground Detonations", "tags": ["building"], "number": "202", "type": "Active",
     "text": "", "ae": "Action: Spend 10 MC to increase your heat production 2 steps."},
    {"price": "6", "name": "Urban Decomposers", "tags": ["microbe"], "number": "C48", "type": "Automated",
     "text": "Requires that you have 1 city tile and 1 colony in play. Increase your plant production 1 step, and add 2 microbes to ANOTHER card.",
     "ae": ""},
    {"price": "10", "name": "Urbanized Area", "tags": ["building", "city"], "number": "120", "type": "Automated",
     "text": "Decrease your energy production 1 step and increase your MC production 2 steps. Place a city tile ADJACENT TO AT LEAST 2 OTHER CITY TILES.",
     "ae": ""},
    {"price": "4", "name": "Venus Governor", "tags": ["venus", "venus"], "number": "255", "type": "Automated",
     "text": "Requires 2 Venus tags. Increase your MC production 2 steps.", "ae": ""},
    {"price": "7", "name": "Venus Magnetizer", "tags": ["venus"], "number": "256", "type": "Active",
     "text": "Requires Venus 10%", "ae": "Action: Decrease your energy production 1 step to raise Venus 1 step."},
    {"price": "20", "name": "Venus Soil", "tags": ["plant", "venus"], "number": "257", "type": "Automated",
     "text": "Raise Venus 1 step. Increase your plant production 1 step. Add 2 microbes to ANOTHER card.", "ae": ""},
    {"price": "9", "name": "Venus Waystation", "tags": ["space", "venus"], "number": "258", "type": "Active",
     "text": "", "ae": "Effect: When you play a Venus tag, you pay 2 MC less for it."},
    {"price": "15", "name": "Venusian Animals", "tags": ["science", "animal", "venus"], "number": "259",
     "type": "Active", "text": "Requires Venus 18%. 1 VP for each animal on this card.",
     "ae": "Effect: When you play a science tag, including this, add 1 animal to this card."},
    {"price": "5", "name": "Venusian Insects", "tags": ["microbe", "venus"], "number": "260", "type": "Active",
     "text": "Requires Venus 12%. 1 VP per 2 microbes on this card.", "ae": "Action: Add 1 microbe to this card."},
    {"price": "13", "name": "Venusian Plants", "tags": ["microbe", "venus"], "number": "261", "type": "Automated",
     "text": "Requires Venus 16%. Raise Venus 1 step. Add 1 microbe or 1 animal to ANOTHER VENUS CARD.", "ae": ""},
    {"price": "15", "name": "Vesta Shipyard", "tags": ["space", "jovian"], "number": "57", "type": "Automated",
     "text": "Increase your titanium production 1 step.", "ae": ""},
    {"price": "9", "name": "Viral Enhancers", "tags": ["science", "microbe"], "number": "74", "type": "Active",
     "text": "",
     "ae": "Effect: When you play a plant, microbe, or an animal tag, including this, gain 1 plant or add 1 resource TO THAT CARD."},
    {"price": "1", "name": "Virus", "tags": ["microbe", "event"], "number": "50", "type": "Event",
     "text": "Remove up to 2 animals or 5 plants from any player.", "ae": ""},
    {"price": "14", "name": "Warp Drive", "tags": ["science"], "number": "C49", "type": "Active",
     "text": "Requires 5 science tags.", "ae": "Effect: When you play a space tag, you pay 4 MC less for it."},
    {"price": "25", "name": "Water Import From Europa", "tags": ["space", "jovian"], "number": "12", "type": "Active",
     "text": "1 VP for each Jovian tag you have.",
     "ae": "Action: Pay 12 MC to place an ocean tile. TITANIUM MAY BE USED as if playing a space card."},
    {"price": "12", "name": "Water Splitting Plant", "tags": ["building"], "number": "177", "type": "Active",
     "text": "Requires 2 ocean tiles.", "ae": "Action: Spend 3 energy to raise oxygen 1 step."},
    {"price": "9", "name": "Water to Venus", "tags": ["space", "event"], "number": "254", "type": "Event",
     "text": "Raise Venus 1 step.", "ae": ""},
    {"price": "8", "name": "Wave Power", "tags": ["energy"], "number": "139", "type": "Automated",
     "text": "Requires 3 ocean tiles. Increase your energy production 1 step.", "ae": ""},
    {"price": "6", "name": "Windmills", "tags": ["building", "energy"], "number": "168", "type": "Automated",
     "text": "Requires 7% oxygen. Increase your energy production 1 step.", "ae": ""},
    {"price": "8", "name": "Worms", "tags": ["microbe"], "number": "130", "type": "Automated",
     "text": "Requires 4% oxygen. Increase your plant production 1 step for every 2 microbe tags you have, including this.",
     "ae": ""}, {"price": "13", "name": "Zeppelins", "tags": [], "number": "129", "type": "Automated",
                 "text": "Requires 5% oxygen. Increase your MC production 1 step for each city tile ON MARS.",
                 "ae": ""}]}
cards = {v["number"]: v["name"] for v in game_data["cards"]}

@app.route('/update', methods=["POST"])
def get_state():
    content = request.json

    for k, v in content.items():
        content[k]["CardsPlayed"] = [cards[str(card_number)] for card_number in content[k]["CardsPlayed"]]
        content[k]["CardsInHand"] = [cards[str(card_number)] for card_number in content[k]["CardsInHand"]]

    socketio.emit("update", content)

    return jsonify(success=True)


@app.route("/")
def home():
    return app.send_static_file("index.html")


@socketio.on('connect')
def connect():
    print("Client connected")


@socketio.on('disconnect')
def disconnect():
    print('Client disconnected')


if __name__ == '__main__':
    socketio.run(app, debug=True)
